apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-flannel-cfg
  namespace: kube-flannel
data:
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "EnableNFTables": true,
      "Interface": "wg0"
      "Backend": {
        "Type": "host-gw"
      },
    }